services:
  app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - "${DB_HOST}"
    environment:
      - PORT=${PORT}
      - DB_HOST=${DB_HOST}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - NUBEFACT_API_URL=${NUBEFACT_API_URL}
      - NUBEFACT_API_TOKEN=${NUBEFACT_API_TOKEN}

  db:
    image: mysql:8.0
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      - DB_PORT=${DB_PORT}
      - MYSQL_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
